### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by mrbig00** [wnetking/reactive-prestashop#1]
Firstly congratulations on this module initiative!

It's really fast and gives the user incredible smoothness. I've found only one thing that if  navigate from the homepage to another (for example: a product), if I reload the page I've got a 404 page. This is probably because you are rewriting the urls on browser level only.

Are you planning on developing this module? If yes, I would be more than happy to help.

**Comment by illia-krlv** [comment]
Hi, thanks for you review. 
I know about this bug. I just no have much time that sat and resolved it) 
Yes, in future i planning developed it. If you have some ideas I listen =)

**Comment by mrbig00** [comment]
Hi,

I have a few ideas, I will make a pull request and lets see how things gonna work :)
