### ISSUE TITLE
thanks, information

### ISSUE THREAD

**Issue by sitolab** [wnetking/reactive-prestashop#2]
hello, I saw your work and I must say that it is very satisfactory, but I would like to ask you a question, I do not see the cart, and I can not log in or register as a customer, which files should I display to be able to enter the missing information? (example: shopping cart, registration and customer access, contact page etc. etc.)

thank you

**Comment by illia-krlv** [comment]
Hi, thanks for you issues! 
Cart, login and registration - all this features not support yet, it's future plans.
If you have some idea on module development create pull request, I will gladly consider it :)

Best regards!

**Comment by MaxInMoon** [comment]
@wnetking do you have an idea about how to set the authentification part (login and registration)? thanks

**Comment by illia-krlv** [comment]
@MaxInMoon You can implement this feature in module backend part

**Comment by MaxInMoon** [comment]
@wnetking what do you call the "module backend"? I don't know where to start

**Comment by illia-krlv** [comment]
@MaxInMoon 
This module use Prestashop **websevice**, and you can find all what you need in webservice documentation. 
http://doc.prestashop.com/display/PS16/Chapter+3+-+First+steps+-+Accessing+the+web+service+and+listing+customers?_ga=2.77095697.582011552.1539633885-2056191611.1539633885

For make authentification part you need use **POST** query, its posibly only from backend. 

_PrestaShop-webservice-lib_ help you do this easily.
https://github.com/PrestaShop/PrestaShop-webservice-lib   

Hope this help you =)

**Comment by mrbig00** [comment]
The PS webservice does not provide tokens for clients and users, however it can be implemented easily. I can do the back-end part, but unfortunately I'm not good with front-end stuff like React'n'stuff.

**Comment by illia-krlv** [comment]
@mrbig00 Nice to hear it =)
It's be awesome if you can do some REST API in module backend, and I can do frontend part.
